name: Nightly Test  

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ${{ vars.RUNNER_RUNS_ON }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: |
          **/go.mod
          **/go.sum

    - name: Install dependencies
      run: go mod download

    - name: Run Unit Tests
      run: |
        go test -v -race -coverprofile=coverage.out ./...
    
    - name: Run Examples
      env:
        MGC_API_TOKEN: ${{ secrets.MGC_API_TOKEN }}
      run: |
        go run cmd/examples/main.go