name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: |
          **/go.mod
          **/go.sum

    - name: Install dependencies
      run: go mod download

    - name: Run Unit Tests
      run: |
        go test -v -race -coverprofile=coverage.out ./...
    

    - name: Upload Coverage Report to SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.login=${{ secrets.MAGALUBOT_SONAR_TOKEN }}