name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Run Unit Tests
      run: |
        mkdir -p .octocov
        go test -v -race ./...

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      env:
        SONAR_TOKEN: ${{ secrets.ORG_SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.ORG_SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
          -Dsonar.sources=.
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*_test.go
          -Dsonar.go.coverage.reportPaths=coverage.out        